apiVersion: v1
kind: deploy
metadata:
  name: general-HOST_POD
spec:
  containers:
  - name: general-HOST_POD
    image: ryansavordelli/general-image:TAG_IMAGE
    command: ["/bin/sh", "-c"]
    args: ["while true; do echo 'Container is running...'; sleep 10; done"]    
    ports:
    - containerPort: 80